---
- name: install nginx, mysql, php, git, vim, zsh
  hosts: dev-server
  # user: vagrant
  sudo : yes
  roles:
    - common
    - mysql
    - nginx
    - php55
    - git
    - zsh
    - vim
    - chara

    ## 予備roles
    # - apache # can't use with nginx
    # - jenkins
