---
- name: install base server
  hosts: dev-server
  # user: vagrant
  sudo : yes
  roles:
    - common
    - git
    - zsh
    - vim
    - chara

    ## 予備roles
    # - apache # can't use with nginx
    # - jenkins
