---
- name: clone dotfiles
  git: repo=https://github.com/matsu-chara/dotfiles/ {{ dotfiles_dir }}/.dotfiles
  sudo: yes
  sudo_user: {{ user }}

- name: setup
  command: |
    chmod u+x {{ dotfiles_dir }}/.dotfiles/setup.sh &&
    {{ dotfiles_dir }}/.dotfiles/setup.sh &&
  sudo: yes
  sudo_user: {{ user }}

- name: change login shell
  command: chsh -s /usr/local/bin/zsh {{ user }}


