---
- name: install git-dependencies
  yum: name={{ item }} state=present
  with_items:
  - curl-devel
  - expat-devel
  - gettext-devel
  - openssl-devel
  - zlib-devel
  - perl-ExtUtils-MakeMaker

- name: get source
  get_url: url=https://www.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz dest={{ src }}

- name: unarchive source
  command: tar zxvf git-{{ version }}.tar.gz chdir={{ src }} creates={{ src }}/git-{{ version }}

- name: make
  command: make prefix=/usr/local all chdir={{ src }}/git-{{ version }}

- name: make install
  command: make prefix=/usr/local install chdir={{ src }}/git-{{ version }}
