---
- name: install libselinux-python for lineinfile
  yum: name=libselinux-python state=present

- name: set time zone to Asia/Tokyo(1/2)
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes

- name: set time zone to Asia/Tokyo(2/2)
  copy: src=clock dest=/etc/sysconfig/clock

- name: yum repository use only jp server
  lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf line="include_only=.jp"

- name: update all package
  yum: name=* state=latest

# EPEL
- name: install the epel gpg key
  rpm_key: key=http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-5

- name: install the epel repo
  yum: name=http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

# RPM Forge
- name: install the rpmforce gpg key
  rpm_key: key=http://apt.sw.be/RPM-GPG-KEY.dag.txt state=present

- name: install the rpmforge repo
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm state=present

# REMI
- name: install the remi gpg key
  rpm_key: key=http://rpms.famillecollet.com/RPM-GPG-KEY-remi

- name: install the remi repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

# DEV TOOL
- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install httpd-tolls for htpasswd
  yum: name=httpd-tools state=present
